added a better configure script, and used some of the options like VERSION and PACKAGE

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1263,11 +1263,15 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 PACKAGE=jailkit
-VERSION=0.4
+VERSION=pre0.4
 
 
 cat >>confdefs.h <<_ACEOF
 #define PACKAGE "$PACKAGE"
+_ACEOF
+
+cat >>confdefs.h <<_ACEOF
+#define VERSION "$VERSION"
 _ACEOF
 
 
@@ -2832,47 +2836,6 @@ fi
 
 
 
-# Extract the first word of "python", so it can be a program name with args.
-set dummy python; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_HAVE_PYTHON+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$HAVE_PYTHON"; then
-  ac_cv_prog_HAVE_PYTHON="$HAVE_PYTHON" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_HAVE_PYTHON="no"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-HAVE_PYTHON=$ac_cv_prog_HAVE_PYTHON
-if test -n "$HAVE_PYTHON"; then
-  echo "$as_me:$LINENO: result: $HAVE_PYTHON" >&5
-echo "${ECHO_T}$HAVE_PYTHON" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-if test "x$HAVE_PYTHON" = "xno" ; then
-	{ { echo "$as_me:$LINENO: error: python not found please install python" >&5
-echo "$as_me: error: python not found please install python" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
 # On IRIX 5.3, sys/types and inttypes.h are conflicting.
 
 
@@ -3150,6 +3113,47 @@ echo "$as_me: error: libpthread not found" >&2;}
 
 fi
 
+
+# Extract the first word of "python", so it can be a program name with args.
+set dummy python; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_HAVE_PYTHON+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$HAVE_PYTHON"; then
+  ac_cv_prog_HAVE_PYTHON="$HAVE_PYTHON" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_HAVE_PYTHON="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+HAVE_PYTHON=$ac_cv_prog_HAVE_PYTHON
+if test -n "$HAVE_PYTHON"; then
+  echo "$as_me:$LINENO: result: $HAVE_PYTHON" >&5
+echo "${ECHO_T}$HAVE_PYTHON" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "x$HAVE_PYTHON" != "xyes" ; then
+	{ { echo "$as_me:$LINENO: error: python not found please install python" >&5
+echo "$as_me: error: python not found please install python" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
                                         ac_config_files="$ac_config_files Makefile src/Makefile py/Makefile man/Makefile"
 
